### ISSUE TITLE
Getting error always on executing AccountKit.getCurrentAccount

### ISSUE THREAD

**Issue by pstuashiqcse** [elaniin/AccountKit-Android-Java#1]
I'm always getting this error - 200: Server generated an error: 145: API calls from the server require an appsecret_proof argument

Could you please help regarding this. I do believe there is a workaround in Facebook app security configuration.

**Comment by adriangomezme** [comment]
One way that I was able to put it working, was by setting to `No` the `App Secret proof for API calls` in the advanced settings of the Facebook App.
**However, this is a fix, not a solve.**

The other way is by adding a parameter `appsecret_proof` to your request containg a `sha256` hash of `accessToken`and `appSecret`
[https://developers.facebook.com/docs/graph-api/securing-requests](url)

**Comment by GeoffreyPlitt** [comment]
I have the settings turned on exactly as recommended and STILL get this error, but only on LTE, not on Wifi. https://imgur.com/a/DQZLa
